### ISSUE TITLE
SPIKE: Add environment switch/deploy equivilants

### ISSUE THREAD

**Issue by dafeder** [GetDKAN/dkan-tools#2]
I want to have a safe development environment that has all the modules I know I need enabled.

When I pull the production DB to my dev environment, I want operations specific to that transition to happen before I start working on my local environment.

When I push new code and the CI server pulls the code to run tests, I want a second set of operations specific to that transition to happen before tests run.

I want a minimum of confusion about where environment switching logic occurs.

Create a second ticket with full implementation details and acceptance criteria.

Child of #16

**Comment by dafeder** [comment]
I want to have a safe development environment that has all the modules I know I need enabled.

When I pull the production DB to my dev environment, I want operations specific to that transition to happen before I start working on my local environment.

When I push new code and the CI server pulls the code to run tests, I want a second set of operations specific to that transition to happen before tests run.

I want a minimum of confusion about where environment switching logic occurs.

Create a second ticket with full implementation details and acceptance criteria.

Child of #16

**Comment by acouch** [comment]
## Proposal

### Current Setup

Environment switching is placed in bash scripts, settings.php files, features master calls and config.yml files.

### New Setup

Move all of that to data_config and custom_config modules and use ``hook_environment_switch()`` and ``hook_init`` to turn on and off modules and set variables. This means removing:

#### Remove

* config.yml file (move items to data_config and custom_config)
* all ahoy stuff
* .ahoy/site/.scripts folder
* multiple deploy scripts

#### Keep
* settings.acquia.php (unfortunately)
* settings.custom.php (created by ``dktl init``)
* settings.php (move most of this out to data_config but keep links to other settings files)

#### Move
* memache settings (settings.acquia.php to settings.custom.php)
* all env switching, module lists, and variable setting from ``settings.php`` to data_config
* use ``hook_update_N()`` for updates

#### Special considerations

* secure pages settings have some logic
* create 'probo' environment instead of 'ci'?
* way to add new settings.php files other than sticking them in dkan-tools. could this be module based?

## Pros
* MUCH simpler, all custom stuff data config module and out of various settings files and deployment scripts
* remove ``config.yml`` which was never fully realized and created an ugly abstraction

## Cons
* using variable_set (maybe create a ``data_config_variable_set()`` function) might take longer
* using variable_set instead of $CONF might cause problems since it is not done on every request, just during env-switch

**Comment by acouch** [comment]
> When I pull the production DB to my dev environment, I want operations specific to that transition to happen before I start working on my local environment.

The steps for this are to run the deploy script ``dktl deploy`` which runs the environment switch. Currently the deploy script runs three different bash files. Then environment switching happens in several different places. I'm proposing using a single deploy script that simply runs:

```bash

drush rr
drush cc all
drush updatedb
drush env-switch ENV --force

```

The environment switch can be controlled using ``hook_environment_switch()``. Right not the environment switching happens in like 5 places. I would remove it from most of the settings.php files and add to ``custom_config`` module or create a ``dkan_environment`` module.

**Comment by acouch** [comment]
We've agreed on everything:

> Create a second ticket with full implementation details and acceptance criteria.

Doing this in #18
