### ISSUE TITLE
SPIKE: Deployment script

### ISSUE THREAD

**Issue by dafeder** [GetDKAN/dkan-tools#21]
Currently there is a deployment script built into DKAN starter. The environment switch is part of this, but the deployment script is broader and run in _all_ environments upon deployment, including steps like registry rebuild, updb, etc. Some equivalent of this is still needed and must work with Acquia deployment hooks, but the current architecture is very hard to understand and could be greatly simplified.

Goals:

* Reduce complexity
* No ruby
* Run by Acquia hooks but not acquia-dependent
* Move more things from deployment script to install files
* Allow for custom deployment scripts? 

Implementation? 

Child of #16

**Comment by acouch** [comment]
### Current setup:

#### 1. run [ahoy ci deploy](https://github.com/GetDKAN/dkan_starter/blob/master/.ahoy/site/ci.ahoy.yml#L9)

This runs:

1. ``ahoy utils truncate watchdog`` (not sure why this is necessary. lets remove)
2.  ``ahoy cmd-proxy bash hooks/common/post-code-deploy/drush-env-switch.sh $name $env``

#### 2. [drush-env-switch.sh](https://github.com/GetDKAN/dkan_starter/blob/master/hooks/common/post-code-update/drush-env-switch.sh)

Takes two args (site name, environment).

It translates environment to the string environment module expects:

<details>
<summary>bash non-sense to remove</summary>

```bash

env_map=(
  "local:local"
  "pro:production"
  "prod:production"
  "production:production"
  "dev:development"
  "test:test"
  "ra:test"
  "testing:test"
  "lt:test"
)

for m in "${env_map[@]}"; do
  target_key=$(echo $m | cut -d: -f1)
  if [ "$target_key" = "$env" ]; then
    echo $m
    target_env=$(echo $m | cut -d: -f2)
   break
  fi  
done
```
</details>

Then checks if we are in Acquia and then runs:

```bash

target_env=$target_env bash ../.ahoy/site/.scripts/upgrade-deploy.sh

```

#### 3. [upgrade-deploy.sh](https://github.com/GetDKAN/dkan_starter/blob/master/.ahoy/site/.scripts/upgrade-deploy.sh)

This runs an upgrade specific script:

```bash

drush_cmd bash .ahoy/site/.scripts/upgrades/$upgrade_version.sh

```
Then a deploy script:

```bash

 target_env=$target_env bash .ahoy/site/.scripts/deploy.sh

```

#### 4. [deploy.sh](https://github.com/GetDKAN/dkan_starter/blob/master/.ahoy/site/.scripts/deploy.sh)

This is the command we may want to keep. When deploying we want to:

1. Run **cache clear** and **registry rebuild**. Why? Because if modules move around you want to run registry rebuild and any update you want to clear the cache.
2. Run **environment switch** and **updatedb** .These are things we also want to continue to run every time.

**Comment by acouch** [comment]
## Proposal

Keep ``hooks/common/post-code-deploy/deploy.sh`` but reduce it to:

```bash

drush rr
drush cc all
drush env-switch $ENV --force
drush updatedb
```

MOVE ALL OF THE ENVIRONMENT SWITCHING AND OTHER DEPLOY STUFF TO CUSTOM MODULE USING HOOK_ENVIRONMENT_SWITCH()

see: https://github.com/GetDKAN/dkan-tools/issues/2
